#!/usr/bin/expect -f

set IP	   [lindex $argv 0]	
set USER   root

spawn ssh -i /home/vagrant/.ssh/id_rsa $USER@$IP
expect {
    "(yes/no)?" {
        send "yes\r"
        }
    }
sleep 1

expect "*#"
 
send "curl -O https://raw.githubusercontent.com/sjh-0504/digitalocean_auto_install/main/wg_mult.sh && chmod +x wg_mult.sh && ./wg_mult.sh\n"

expect "*#"
sleep 1
send "\n"

interact
